export default [{
  id: '1175391328010401973_1453092205',
  like: 115,
  comment: 2,
  tags: ['dog',
    'norfolkterrier',
    'dog_features',
    'cutedog',
    'blackandtan',
    'petsofig',
    'ilovedog',
    'life',
    'cute',
    'dogs_of_instagram',
    'precious',
    'photooftheday',
    'doglover',
    'dogsoftheworld',
    'doglife',
    'instadog',
    'nature',
    'happy_pet',
    'norfolkterriers',
    'pet',
    'terrier',
    'weeklyfluff',
    'dogstagram',
    'puppy',
    'instagood',
    'puppiesofinstagram',
    'petbox'
  ]
}, {
  id: '1174242388045101238_1453092205',
  like: 140,
  comment: 1,
  tags: ['dog',
    'norfolkterrier',
    'norfolkterriersofinstagram',
    'doglovers',
    'animallovers',
    'petsofinstagram',
    'bestwoof',
    'lovedogs',
    'topdogphoto',
    'dailyfluff',
    'excellent_dogs',
    'pup',
    'dogs',
    'dogs_of_world',
    'petscorner',
    'photooftheday',
    'ilovemydog',
    'puppylove',
    'hounds',
    'petstagram',
    'precious',
    'petsofig',
    'dogoftheday',
    'woof_tastic',
    'animales',
    'puppylover',
    'animals'
  ]
}, {
  id: '1173510754207431256_1453092205',
  like: 133,
  comment: 1,
  tags: ['dog',
    'norfolkterrier',
    'petsofig',
    'dogs_of_world',
    'woof_tastic',
    'doglover',
    'ilovemydog',
    'petscorner',
    'doggy',
    'precious',
    'cutedog',
    'dog_features',
    'dailyfluff',
    'excellent_dogs',
    'instaterrier',
    'animals',
    'picpets',
    'ilovedogs',
    'hound',
    'lovepuppies',
    'petsofinstagram',
    'petbox',
    'dogslife',
    'dogsoftheworld',
    'petstagram',
    'animal',
    'blacktan'
  ]
}, {
  id: '1172495233559198500_1453092205',
  like: 133,
  comment: 0,
  tags: ['dog',
    'norfolkterrier',
    'puppylover',
    'bestwoof',
    'puppies',
    'dog_features',
    'dogstagram',
    'dailydog',
    'terrierstagram',
    'dogslife',
    'hounds',
    'norfolkterriersofinstagram',
    'instapuppy',
    'photooftheday',
    'woof_tastic',
    'ilovemydog',
    'doggie',
    'petbox',
    'terrier',
    'topdogphoto',
    'doglife',
    'blacktan',
    'dailyfluff',
    'animal',
    'instagramdogs',
    'petstagram',
    'cutedog'
  ]
}, {
  id: '1171749111488215114_1453092205',
  like: 151,
  comment: 0,
  tags: ['dog',
    'norfolkterrier',
    'terriers',
    'norfolkterriers',
    'instaterrier',
    'puppies',
    'blackandtan',
    'petstagram',
    'instapet',
    'petsofig',
    'dogsofig',
    'cutie',
    'pet',
    'lovepuppies',
    'animales',
    'nature',
    'love',
    'animallovers',
    'animals',
    'doglife',
    'petscorner',
    'instagood',
    'dogoftheday',
    'petsagram',
    'pets_of_instagram',
    'dogs_of_instagram',
    'instadog'
  ]
}, {
  id: '1171061695873973087_1453092205',
  like: 149,
  comment: 1,
  tags: ['dog',
    'norfolkterrier',
    'instagood',
    'dailydog',
    'terriers',
    'lovedogs',
    'petbox',
    'blacktan',
    'blackandtan',
    'norfolkterriers',
    'terrier',
    'doggy',
    'instapet',
    'dogs',
    'dog_features',
    'dogslife',
    'norfolkterriersofinstagram',
    'cutedog',
    'hound',
    'pup',
    'ilovedog',
    'ilovemydog',
    'dailyfluff',
    'doglovers',
    'dogstagram',
    'petsofinstagram',
    'animal'
  ]
}, {
  id: '1170540977167956163_1453092205',
  like: 151,
  comment: 2,
  tags: ['dog',
    'norfolkterrier',
    'puppiesofinstagram',
    'dailydog',
    'cutedog',
    'instapuppy',
    'ilovedog',
    'puppylover',
    'petsofinstagram',
    'dogs',
    'animal',
    'dogs_of_instagram',
    'dogs_of_world',
    'pet',
    'instagramdogs',
    'animals',
    'dog_features',
    'hounds',
    'dogsofinstagram',
    'lovedogs',
    'petbox',
    'doggie',
    'instagood',
    'dogsofig',
    'precious',
    'picpets',
    'petsofig'
  ]
}, {
  id: '1169683219468155659_1453092205',
  like: 128,
  comment: 7,
  tags: ['kirby',
    'dog',
    'norfolkterrier',
    'petscorner',
    'photooftheday',
    'happy_pet',
    'lovedogs',
    'doggie',
    'animallovers',
    'norfolkterriers',
    'puppiesofinstagram',
    'instagood',
    'dogsofig',
    'hound',
    'bestwoof',
    'norfolkterriersofinstagram',
    'dogs_of_world',
    'hounds',
    'puppylove',
    'petsofig',
    'petsagram',
    'dogsofinstagram',
    'dogstagram',
    'dogs',
    'life',
    'doglovers',
    'smalldog'
  ]
}, {
  id: '1168768945090623515_1453092205',
  like: 131,
  comment: 0,
  tags: ['dog',
    'norfolkterrier',
    'love',
    'terrier',
    'puppylove',
    'dogstagram',
    'animals',
    'dailydog',
    'pets',
    'pup',
    'dogs',
    'animallovers',
    'animal',
    'petstagram',
    'instapet',
    'pets_of_instagram',
    'petsofinstagram',
    'happy_pet',
    'hounds',
    'ilovemydog',
    'blackandtan',
    'pet',
    'norfolkterriers',
    'puppiesofinstagram',
    'dog_features',
    'terriers',
    'smalldog'
  ]
}, {
  id: '1168123653232163076_1453092205',
  like: 162,
  comment: 1,
  tags: ['dog',
    'norfolkterrier',
    'puppy',
    'dogstagram',
    'pets_of_instagram',
    'excellent_dogs',
    'instapuppy',
    'doglover',
    'dogoftheday',
    'pet',
    'instaterrier',
    'dog_features',
    'nature',
    'cutie',
    'petbox',
    'ilovemydog',
    'terriers',
    'instagood',
    'weeklyfluff',
    'life',
    'instagramdogs',
    'ilovedogs',
    'cutedog',
    'puppiesofinstagram',
    'puppylove',
    'petsofinstagram',
    'dailydog'
  ]
}, {
  id: '1167370067053279756_1453092205',
  like: 174,
  comment: 0,
  tags: ['dog',
    'norfolkterrier',
    'animal',
    'dogslife',
    'terrierstagram',
    'doglovers',
    'dogstagram',
    'cutedog',
    'hound',
    'weeklyfluff',
    'animallovers',
    'petbox',
    'life',
    'pup',
    'dogoftheday',
    'dogs_of_instagram',
    'petscorner',
    'precious',
    'petsofinstagram',
    'puppies',
    'puppylover',
    'doglife',
    'picpets',
    'instaterrier',
    'ilovedogs',
    'pets_of_instagram',
    'cute'
  ]
}, {
  id: '1166692159565494590_1453092205',
  like: 161,
  comment: 4,
  tags: ['dog',
    'norfolkterrier',
    'excellent_dogs',
    'happy_pet',
    'puppy',
    'cute',
    'doglover',
    'blackandtan',
    'petsofinstagram',
    'puppylove',
    'norfolkterriers',
    'petsofig',
    'weeklyfluff',
    'puppiesofinstagram',
    'woof_tastic',
    'dogoftheday',
    'puppies',
    'instapuppy',
    'instadog',
    'puppylover',
    'picpets',
    'dogsofinstagram',
    'petbox',
    'ilovedog',
    'dogslife',
    'animal',
    'lovedogs'
  ]
}, {
  id: '1165987106751936988_1453092205',
  like: 171,
  comment: 2,
  tags: ['dog',
    'norfolkterrier',
    'animales',
    'puppylover',
    'dogoftheday',
    'petsagram',
    'pets',
    'animallovers',
    'petstagram',
    'terrier',
    'photooftheday',
    'excellent_dogs',
    'lovepuppies',
    'petbox',
    'pet',
    'dogs',
    'petscorner',
    'life',
    'dogsofinstagram',
    'hounds',
    'precious',
    'ilovedogs',
    'weeklyfluff',
    'ilovemydog',
    'blackandtan',
    'instapet',
    'terriers'
  ]
}, {
  id: '1165167842176432641_1453092205',
  like: 157,
  comment: 0,
  tags: ['dog',
    'norfolkterrier',
    'excellent_dogs',
    'dogs_of_instagram',
    'lovepuppies',
    'petsofig',
    'pets_of_instagram',
    'bestwoof',
    'ilovedog',
    'weeklyfluff',
    'animallovers',
    'doggie',
    'petsagram',
    'petbox',
    'dog_features',
    'adorable',
    'doglife',
    'instagood',
    'cutedog',
    'terrierstagram',
    'doglover',
    'puppiesofinstagram',
    'blackandtan',
    'petsofinstagram',
    'cute',
    'instaterrier',
    'pet'
  ]
}, {
  id: '1164497246845303073_1453092205',
  like: 143,
  comment: 0,
  tags: ['dog',
    'norfolkterrier',
    'petsofig',
    'dailyfluff',
    'dogoftheday',
    'love',
    'cute',
    'instapuppy',
    'precious',
    'blacktan',
    'lovepuppies',
    'topdogphoto',
    'doglovers',
    'animales',
    'dogs_of_instagram',
    'weeklyfluff',
    'puppylover',
    'picpets',
    'instagramdogs',
    'dogsofig',
    'doglife',
    'instapet',
    'happy_pet',
    'pet',
    'dogslife',
    'pets',
    'ilovemydog'
  ]
}, {
  id: '1163755094104242891_1453092205',
  like: 164,
  comment: 0,
  tags: ['dog',
    'norfolkterrier',
    'photooftheday',
    'picpets',
    'dogoftheday',
    'dogsofig',
    'terrierstagram',
    'life',
    'dogslife',
    'dogsofinstagram',
    'animal',
    'dog_features',
    'instapet',
    'petstagram',
    'terriers',
    'excellent_dogs',
    'instagood',
    'doglover',
    'love',
    'pet',
    'doglovers',
    'instagramdogs',
    'weeklyfluff',
    'animales'
  ]
}, {
  id: '1163474658056633073_1453092205',
  like: 158,
  comment: 3,
  tags: ['dog',
    'norfolkterrier',
    'animals',
    'ilovemydog',
    'doggie',
    'petstagram',
    'ilovedog',
    'cutedog',
    'dog_features',
    'instadog',
    'puppiesofinstagram',
    'pup',
    'lovepuppies',
    'puppy',
    'dogslife',
    'cutie',
    'lovedogs',
    'dogoftheday',
    'dogstagram',
    'instapuppy',
    'doglife',
    'dogsofig',
    'puppylover',
    'instapet',
    'blackandtan'
  ]
}, {
  id: '1162384304599366312_1453092205',
  like: 141,
  comment: 0,
  tags: ['dog',
    'norfolkterrier',
    'hounds',
    'cute',
    'precious',
    'animal',
    'instagramdogs',
    'instapet',
    'doglife',
    'pet',
    'petstagram',
    'dogslife',
    'ilovemydog',
    'happy_pet',
    'puppylover'
  ]
}, {
  id: '1161873672087173609_1453092205',
  like: 147,
  comment: 3,
  tags: ['dog',
    'norfolkterrier',
    'ilovedogs',
    'animal',
    'pup',
    'ilovedog',
    'happy_pet',
    'woof_tastic',
    'dogsofinstagram',
    'animallovers',
    'dailydog',
    'dogs',
    'cute',
    'smalldog',
    'doglife',
    'animales',
    'cutedog',
    'instaterrier',
    'lovepuppies',
    'life',
    'blackandtan',
    'lovedogs',
    'doglover',
    'dogsofig',
    'dogs_of_instagram',
    'blacktan',
    'dogstagram'
  ]
}, {
  id: '1161039234860219253_1453092205',
  like: 135,
  comment: 0,
  tags: ['dog',
    'norfolkterrier',
    'bestwoof',
    'adorable',
    'smalldog',
    'doglife',
    'puppylover',
    'animallovers',
    'dogs',
    'blacktan',
    'ilovedog',
    'terriers',
    'love',
    'animals',
    'dogs_of_instagram',
    'petbox',
    'life',
    'dogoftheday',
    'terrier',
    'hounds',
    'blackandtan',
    'instapet',
    'petstagram',
    'cutie',
    'topdogphoto'
  ]
}]

export const masterTags = [ 
  'adorable',
  'animal',
  'animales',
  'animallovers',
  'animals',
  'bestwoof',
  'blackandtan',
  'blacktan',
  'cute',
  'cutedog',
  'cutie',
  'dailydog',
  'dailyfluff',
  'dog_features',
  'doggie',
  'doggy',
  'doglife',
  'doglover',
  'doglovers',
  'dogoftheday',
  'dogs',
  'dogs_of_instagram',
  'dogs_of_world',
  'dogslife',
  'dogsofig',
  'dogsofinstagram',
  'dogsoftheworld',
  'dogstagram',
  'excellent_dogs',
  'happy_pet',
  'hound',
  'hounds',
  'ilovedog',
  'ilovedogs',
  'ilovemydog',
  'instadog',
  'instagood',
  'instagramdogs',
  'instapet',
  'instapuppy',
  'instaterrier',
  'life',
  'love',
  'lovedogs',
  'lovepuppies',
  'nature',
  'norfolkterriers',
  'norfolkterriersofinstagram',
  'pet',
  'petbox',
  'pets',
  'pets_of_instagram',
  'petsagram',
  'petscorner',
  'petsofig',
  'petsofinstagram',
  'petstagram',
  'photooftheday',
  'picpets',
  'precious',
  'pup',
  'puppies',
  'puppiesofinstagram',
  'puppy',
  'puppylove',
  'puppylover',
  'smalldog',
  'terrier',
  'terriers',
  'terrierstagram',
  'topdogphoto',
  'weeklyfluff',
  'woof_tastic' ]